DeuxièmePartieFormation/Banque/Models/Compte.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Banque.Models
{
    public class Compte
    {
        private int id;
        private decimal solde;
        private Client client;

        public int Id { get => id; set => id = value; }
        [Required]
        [Column(TypeName = "money")]
        [DataType(DataType.Currency)]
        [Range(-5000.0, 1000000000.0)]
        public decimal Solde { get => solde; set => solde = value; }
        [Required]
        public int ClientId { get; set; }
        [ForeignKey("ClientId")]
        public Client Client { get => client; set => client = value; }
        public IEnumerable<Operation> Operations { get; set; }
        public string Discriminator { get; set; }

        public Compte()
        {
            Operations = new List<Operation>();
        }
    }
}

DeuxièmePartieFormation/Banque/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Banque.Data;
using Banque.Models;

namespace Banque.Controllers
{
    public class ClientsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .Include(c => c.Comptes)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom,Prenom,Email,Telephone")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Prenom,Email,Telephone")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Clients.FindAsync(id);
            _context.Clients.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _context.Clients.Any(e => e.Id == id);
        }
    }
}

DeuxièmePartieFormation/Banque/Controllers/ComptesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Banque.Data;
using Banque.Models;

namespace Banque.Controllers
{
    public class ComptesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private Dictionary<string, string> typesComptes = new Dictionary<string, string>()
        {
            {nameof(Compte), "Compte" },
            {nameof(CompteEpargne), "Compte Epargne" },
            {nameof(ComptePayant), "Compte Payant" }
        };

        public ComptesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Comptes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Comptes.Include(c => c.Client);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Comptes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compte = await _context.Comptes
                .Include(c => c.Client)
                .Include(c => c.Operations)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (compte == null)
            {
                return NotFound();
            }

            return View(compte);
        }

        // GET: Comptes/Create
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Email");
            ViewData["TypesComptes"] = new SelectList(typesComptes, "Key", "Value");
            return View();
        }

        // POST: Comptes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Solde,ClientId,Discriminator,Taux,CoutOperation")] ToutCompteDTO compte)
        {
            if (ModelState.IsValid)
            {
                if (compte.Discriminator == "CompteEpargne" && compte.Taux != null)
                {
                    CompteEpargne compteEpargne = new CompteEpargne()
                    {
                        Solde = compte.Solde,
                        ClientId = compte.ClientId,
                        Taux = (decimal)compte.Taux,
                    };
                    _context.Add(compteEpargne);
                }
                else if (compte.Discriminator == "ComptePayant" && compte.CoutOperation != null)
                {
                    ComptePayant comptePayant = new ComptePayant()
                    {
                        Solde = compte.Solde,
                        ClientId = compte.ClientId,
                        CoutOperation = (decimal)compte.CoutOperation,
                    };
                    _context.Add(comptePayant);
                }
                else if (compte.Discriminator == "Compte")
                {
                    _context.Add(compte);
                }
                else
                    return BadRequest("Error during creation of an account");
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Email", compte.ClientId);
            ViewData["TypesComptes"] = new SelectList(typesComptes, "Key", "Value");
            return View(compte);
        }

        // GET: Comptes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compte = await _context.Comptes.FindAsync(id);
            if (compte == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Email", compte.ClientId);
            return View(compte);
        }

        // POST: Comptes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Solde,ClientId")] Compte compte)
        {
            if (id != compte.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compte);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompteExists(compte.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Email", compte.ClientId);
            return View(compte);
        }

        // GET: Comptes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compte = await _context.Comptes
                .Include(c => c.Client)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (compte == null)
            {
                return NotFound();
            }

            return View(compte);
        }

        // POST: Comptes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var compte = await _context.Comptes.FindAsync(id);
            _context.Comptes.Remove(compte);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompteExists(int id)
        {
            return _context.Comptes.Any(e => e.Id == id);
        }
    }
}

DeuxièmePartieFormation/Banque/Controllers/OperationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Banque.Data;
using Banque.Models;

namespace Banque.Controllers
{
    public class OperationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OperationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Operations
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Operations.Include(o => o.Compte);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Operations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var operation = await _context.Operations
                .Include(o => o.Compte)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (operation == null)
            {
                return NotFound();
            }

            return View(operation);
        }

        // GET: Operations/Create
        public IActionResult Create()
        {
            //IEnumerable<Compte> comptes = _context.Comptes;//.Concat(_context.ComptesEpargnes).Concat(_context.ComptesPayants);
            ViewData["CompteId"] = new SelectList(_context.Comptes, "Id", "Id");
            return View();
        }

        // POST: Operations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Montant,DateOperation,CompteId")] Operation operation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(operation);
                Compte compte = _context.Comptes.FirstOrDefault(c => c.Id == operation.CompteId);
                compte.Solde += operation.Montant;
                if (_context.Comptes.Find(operation.CompteId) is ComptePayant comptePayant && comptePayant.Discriminator == nameof(ComptePayant))
                {
                    _context.Add
                        (
                            new Operation()
                            {
                                DateOperation = DateTime.Now,
                                CompteId = operation.CompteId,
                                Montant = -comptePayant.CoutOperation
                            }
                        );
                    compte.Solde -= comptePayant.CoutOperation;
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompteId"] = new SelectList(_context.Comptes, "Id", "Discriminator", operation.CompteId);
            return View(operation);
        }

        // GET: Operations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var operation = await _context.Operations
                .Include(o => o.Compte)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (operation == null)
            {
                return NotFound();
            }

            return View(operation);
        }

        // POST: Operations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var operation = await _context.Operations.FindAsync(id);
            _context.Operations.Remove(operation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OperationExists(int id)
        {
            return _context.Operations.Any(e => e.Id == id);
        }
    }
}

DeuxièmePartieFormation/Banque/Views/Comptes/Create.cshtml
@model Banque.Models.ToutCompteDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Compte</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Discriminator" class="control-label">Type de Compte</label>
                <select asp-for="Discriminator" class ="form-control" asp-items="ViewBag.TypesComptes"></select>
            </div>
            <div class="form-group">
                <label asp-for="Solde" class="control-label"></label>
                <input asp-for="Solde" class="form-control" />
                <span asp-validation-for="Solde" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class ="form-control" asp-items="ViewBag.ClientId"></select>
            </div>
            @*possibilité d'ajouter un controle coté front pour vérifier que les champs suivants soient saisis selon le type compte selectionné*@
            <div class="form-group"> 
                <label asp-for="Taux" class="control-label"></label>
                <input asp-for="Taux" class="form-control" />
                <span asp-validation-for="Taux" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoutOperation" class="control-label"></label>
                <input asp-for="CoutOperation" class="form-control" />
                <span asp-validation-for="CoutOperation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DeuxièmePartieFormation/Banque/Views/Comptes/Delete.cshtml
@model Banque.Models.Compte

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Compte</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Solde)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Solde)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            <a asp-controller="Clients" asp-action="Details" asp-route-id="@Model.Client.Id">@Html.DisplayFor(model => model.ClientId)</a>
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DeuxièmePartieFormation/Banque/Views/Comptes/Details.cshtml
@model Banque.Models.Compte

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Compte</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Solde)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Solde)
        </dd>
        <dt class = "col-sm-2">
            Type de Compte
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discriminator)
        </dd>
        @if (Model is CompteEpargne compteEpargne)
        {
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => compteEpargne.Taux)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => compteEpargne.Taux) %
            </dd>
            @*Ajouter ici la fonctionnalité pour calculer les interrets en appelant une nouvelle méthode du controlleur*@
        }
        @if (Model is ComptePayant comptePayant)
        {
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => comptePayant.CoutOperation)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => comptePayant.CoutOperation)
            </dd>
        }
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            <a asp-controller="Clients" asp-action="Details" asp-route-id="@Model.Client.Id">@Html.DisplayFor(model => model.ClientId)</a>
        </dd>
    </dl>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Operations.FirstOrDefault().Montant)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Operations.FirstOrDefault().DateOperation)
                </th>
                <th>
                    Type d'Opération
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model.Operations) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Montant)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOperation)
                </td>
                <td>
                    @(item.Montant >= 0 ? "Dépôt" : "Retrait")
                </td>
                <td>
                    <a asp-controller="Operations" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="Operations" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
    }
        </tbody>
</table>
    <a asp-controller="Operations" asp-action="Create">Create New Operation</a>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DeuxièmePartieFormation/Banque/Views/Comptes/Edit.cshtml
@model Banque.Models.Compte

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Compte</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Solde" class="control-label"></label>
                <input asp-for="Solde" class="form-control" />
                <span asp-validation-for="Solde" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DeuxièmePartieFormation/Banque/Views/Comptes/Index.cshtml
@model IEnumerable<Banque.Models.Compte>

@{
    ViewData["Title"] = "Index";
}

<h1>Comptes</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Solde)
            </th>
            <th>
                Type de Compte
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Client)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Solde)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discriminator)
            </td>
            <td>
                <a asp-controller="Clients" asp-action="Details" asp-route-id="@item.ClientId">@Html.DisplayFor(modelItem => item.ClientId)</a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>