AspNetCore/Annuaire/Models/Contact.cs
namespace Annuaire.Models
{
    public class Contact
    {
        private int id;
        private string firstName;
        private string lastName;
        private string phone;

        public Contact()
        {

        }

        public Contact(string firstName, string lastName, string phone)
        {
            this.firstName = firstName;
            this.lastName = lastName;
            this.phone = phone;
        }

        public int Id { get => id; set => id = value; }
        public string FirstName { get => firstName; set => firstName = value; }
        public string LastName { get => lastName; set => lastName = value; }
        public string Phone { get => phone; set => phone = value; }
    }
}

AspNetCore/Annuaire/Controllers/AnnuaireController.cs
using Annuaire.DAO;
using Annuaire.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Annuaire.Controllers
{
    public class AnnuaireController : Controller
    {
        ContactDAO contactDAO = new ContactDAO();

        public IActionResult Index()
        {
            return View(contactDAO.GetAll());
        }

        public IActionResult DetailsContact(int id)
        {
            return View(contactDAO.Get(id));
        }

        public IActionResult FormContact()
        {
            return View();
        }

        public IActionResult SubmitContact(string FirstName, string LastName, string Phone)
        {
            Contact contact = new Contact(FirstName, LastName, Phone);
            contactDAO.Save(contact);
            return View(contact);
        }

        public IActionResult FormUpdateContact(int id)
        {
            return View(contactDAO.Get(id));
        }

        public IActionResult SubmitUpdateContact(int Id, string FirstName, string LastName, string Phone)
        {
            Contact contact = new Contact(FirstName, LastName, Phone) { Id = Id };
            if (contactDAO.Update(contact))
                return View(contact);
            else
            {
                return NotFound();
            }
        }

        public IActionResult DeleteContact(int id)
        {
            return View(contactDAO.Get(id));
        }

        public IActionResult ConfirmDeleteContact(int id)
        {
            contactDAO.Delete(id);
            return View();
        }
    }
}

AspNetCore/Annuaire/Views/Annuaire/ConfirmDeleteContact.cshtml
@{
    ViewData["Title"] = "Contact Supprimé";
}
<div>
    <h1>Contact supprimé !</h1>
</div>

AspNetCore/Annuaire/Views/Annuaire/DeleteContact.cshtml
@model Contact
@{
    ViewData["Title"] = "Supprimer Contact";
}
<div>
    <h1>Contact n°@Model.Id</h1>
    <div class=row>
        <div class="col">@Model.FirstName</div>
        <div class="col">@Model.LastName</div>
        <div class="col">@Model.Phone</div>
        <div class="col"><a asp-controller="Annuaire" asp-action="ConfirmDeleteContact" asp-route-id="@Model.Id" method="POST" class="btn btn-danger">Confirmer la suppression</a></div>
    </div>
</div>

AspNetCore/Annuaire/Views/Annuaire/DetailsContact.cshtml
@model Contact
@{
    ViewData["Title"] = "Details Contact";
}
<div>
    <h1>Details de la Personne n°@Model.Id</h1>
    <div class=row>
        <div class="col">@Model.FirstName</div>
        <div class="col">@Model.LastName</div>
        <div class="col">@Model.Phone</div>
    </div>
</div>

AspNetCore/Annuaire/Views/Annuaire/FormContact.cshtml
@{
    ViewData["Title"] = "Formulaire pour Contact";
}

<div>
    <h1>Ajouter une personne</h1>

    <form enctype="multipart/form-data" asp-controller="Annuaire" asp-action="SubmitContact" method="post">
        <div class="row m-1">
            <input type="text" name="FirstName" class="form-control col p-1" placeholder="Merci de saisir le Prénom" />
        </div>
        <div class="row m-1">
            <input type="text" name="LastName" class="form-control col p-1" placeholder="Merci de saisir le Nom" />
        </div>
        <div class="row m-1">
            <input type="text" name="Phone" class="form-control col p-1" placeholder="Merci de saisir le Téléphone" />
        </div>
        <div class="row m-1">
            <button class="col btn btn-primary" type="submit">Valider</button>
        </div>
    </form>

</div>

AspNetCore/Annuaire/Views/Annuaire/FormUpdateContact.cshtml
@model Contact
@{
    ViewData["Title"] = "Modifier Contact";
}
<div>
    <h1>Contact n°@Model.Id</h1>
    <div class=row>
        <div class="col">@Model.FirstName</div>
        <div class="col">@Model.LastName</div>
        <div class="col">@Model.Phone</div>
    </div>
</div>
<div>
    <h2>Modifier le contact</h2>

    <form enctype="multipart/form-data" asp-controller="Annuaire" asp-action="SubmitUpdateContact" method="post">
        <div class="row m-1">
            <input type="text" name="Id" class="form-control col p-1" value="@Model.Id" readonly >
        </div>
        <div class="row m-1">
            <input type="text" name="FirstName" class="form-control col p-1" placeholder="Merci de saisir le nouveau Prénom" />
        </div>
        <div class="row m-1">
            <input type="text" name="LastName" class="form-control col p-1" placeholder="Merci de saisir le nouveau Nom" />
        </div>
        <div class="row m-1">
            <input type="text" name="Phone" class="form-control col p-1" placeholder="Merci de saisir le nouveau Téléphone" />
        </div>
        <div class="row m-1">
            <button class="col btn btn-danger" type="submit">Confirmer la modification</button>
        </div>
    </form>

</div>

AspNetCore/Annuaire/Views/Annuaire/Index.cshtml
@model List<Contact>
@{
    ViewData["Title"] = "Accueil Annuaire";
}
<div>
    <h1>Accueil Annuaire</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Prénom</th>
                <th scope="col">Nom</th>
                <th scope="col">Téléphone</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Contact p in Model)
            {
                <tr>
                    <th  scope="row">@p.Id</th>
                    <td>@p.FirstName</td>
                    <td>@p.LastName</td>
                    <td>@p.Phone</td>
                    <td><a asp-controller="Annuaire" asp-action="DetailsContact" asp-route-id="@p.Id">Détails</a></td>
                    <td><a asp-controller="Annuaire" asp-action="DeleteContact" asp-route-id="@p.Id">Supprimer</a></td>
                    <td><a asp-controller="Annuaire" asp-action="FormUpdateContact" asp-route-id="@p.Id">Modifier</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

AspNetCore/Annuaire/Views/Annuaire/SubmitContact.cshtml
@model Contact
@{
    ViewData["Title"] = "Contact Sauvegardé";
}
<div>
    <h1>Contact sauvegardé !</h1>
    <h2>Contact n°@Model.Id</h2>
    <div class=row>
        <div class="col">@Model.FirstName</div>
        <div class="col">@Model.LastName</div>
        <div class="col">@Model.Phone</div>
    </div>

</div>

AspNetCore/Annuaire/Views/Annuaire/SubmitUpdateContact.cshtml
@model Contact
@{
    ViewData["Title"] = "Contact Modifié";
}
<div>
    <h1>Contact Modifié !</h1>
    <h2>Contact n°@Model.Id</h2>
    <div class=row>
        <div class="col">@Model.FirstName</div>
        <div class="col">@Model.LastName</div>
        <div class="col">@Model.Phone</div>
    </div>

</div>

AspNetCore/Annuaire/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Annuaire</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Annuaire" asp-action="Index">Annuaire</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Annuaire" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Annuaire" asp-action="FormContact">Formulaire</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Annuaire - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>